disabled_rules:
  - line_length
  - unused_closure_parameter
  - multiple_closures_with_trailing_closure
  - large_tuple
  - todo # TODOs are precisely for reminding me of tasks I'll have to do in the future. If they are flagged as violations, it completely defeats the point.
  - file_length
opt_in_rules:

force_cast: warning
force_try: warning

excluded:
  - Sources/DiscordKit/protos
  - .build

identifier_name:
  min_length:
    warning: 3
    error: 0
  max_length:
    warning: 40
    error: 50
  allowed_symbols: ["_"]
cyclomatic_complexity:
  ignores_case_statements: true
nesting:
  type_level:
    warning: 5
    error: 8

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
