// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Settings/Debug.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct DebugSettings {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var rtcPanelShowVoiceStates: SwiftProtobuf.Google_Protobuf_BoolValue {
    get {return _rtcPanelShowVoiceStates ?? SwiftProtobuf.Google_Protobuf_BoolValue()}
    set {_rtcPanelShowVoiceStates = newValue}
  }
  /// Returns true if `rtcPanelShowVoiceStates` has been explicitly set.
  public var hasRtcPanelShowVoiceStates: Bool {return self._rtcPanelShowVoiceStates != nil}
  /// Clears the value of `rtcPanelShowVoiceStates`. Subsequent reads from it will return its default value.
  public mutating func clearRtcPanelShowVoiceStates() {self._rtcPanelShowVoiceStates = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _rtcPanelShowVoiceStates: SwiftProtobuf.Google_Protobuf_BoolValue? = nil
}

#if swift(>=5.5) && canImport(_Concurrency)
extension DebugSettings: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension DebugSettings: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "DebugSettings"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "rtc_panel_show_voice_states"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._rtcPanelShowVoiceStates) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._rtcPanelShowVoiceStates {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DebugSettings, rhs: DebugSettings) -> Bool {
    if lhs._rtcPanelShowVoiceStates != rhs._rtcPanelShowVoiceStates {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
