// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Settings/Localization.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// ====== Localization ====== //
public struct LocalizationSettings {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var locale: SwiftProtobuf.Google_Protobuf_StringValue {
    get {return _locale ?? SwiftProtobuf.Google_Protobuf_StringValue()}
    set {_locale = newValue}
  }
  /// Returns true if `locale` has been explicitly set.
  public var hasLocale: Bool {return self._locale != nil}
  /// Clears the value of `locale`. Subsequent reads from it will return its default value.
  public mutating func clearLocale() {self._locale = nil}

  public var timezoneOffset: SwiftProtobuf.Google_Protobuf_Int32Value {
    get {return _timezoneOffset ?? SwiftProtobuf.Google_Protobuf_Int32Value()}
    set {_timezoneOffset = newValue}
  }
  /// Returns true if `timezoneOffset` has been explicitly set.
  public var hasTimezoneOffset: Bool {return self._timezoneOffset != nil}
  /// Clears the value of `timezoneOffset`. Subsequent reads from it will return its default value.
  public mutating func clearTimezoneOffset() {self._timezoneOffset = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _locale: SwiftProtobuf.Google_Protobuf_StringValue? = nil
  fileprivate var _timezoneOffset: SwiftProtobuf.Google_Protobuf_Int32Value? = nil
}

#if swift(>=5.5) && canImport(_Concurrency)
extension LocalizationSettings: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension LocalizationSettings: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "LocalizationSettings"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "locale"),
    2: .standard(proto: "timezone_offset"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._locale) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._timezoneOffset) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._locale {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._timezoneOffset {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: LocalizationSettings, rhs: LocalizationSettings) -> Bool {
    if lhs._locale != rhs._locale {return false}
    if lhs._timezoneOffset != rhs._timezoneOffset {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
