// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Settings/UserContent.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct UserContentSettings {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var dismissedContents: Data = Data()

  public var lastDismissedOutboundPromotionStartDate: SwiftProtobuf.Google_Protobuf_StringValue {
    get {return _lastDismissedOutboundPromotionStartDate ?? SwiftProtobuf.Google_Protobuf_StringValue()}
    set {_lastDismissedOutboundPromotionStartDate = newValue}
  }
  /// Returns true if `lastDismissedOutboundPromotionStartDate` has been explicitly set.
  public var hasLastDismissedOutboundPromotionStartDate: Bool {return self._lastDismissedOutboundPromotionStartDate != nil}
  /// Clears the value of `lastDismissedOutboundPromotionStartDate`. Subsequent reads from it will return its default value.
  public mutating func clearLastDismissedOutboundPromotionStartDate() {self._lastDismissedOutboundPromotionStartDate = nil}

  public var premiumTier0ModalDismissedAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _premiumTier0ModalDismissedAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_premiumTier0ModalDismissedAt = newValue}
  }
  /// Returns true if `premiumTier0ModalDismissedAt` has been explicitly set.
  public var hasPremiumTier0ModalDismissedAt: Bool {return self._premiumTier0ModalDismissedAt != nil}
  /// Clears the value of `premiumTier0ModalDismissedAt`. Subsequent reads from it will return its default value.
  public mutating func clearPremiumTier0ModalDismissedAt() {self._premiumTier0ModalDismissedAt = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _lastDismissedOutboundPromotionStartDate: SwiftProtobuf.Google_Protobuf_StringValue? = nil
  fileprivate var _premiumTier0ModalDismissedAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

#if swift(>=5.5) && canImport(_Concurrency)
extension UserContentSettings: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension UserContentSettings: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "UserContentSettings"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "dismissed_contents"),
    2: .standard(proto: "last_dismissed_outbound_promotion_start_date"),
    3: .standard(proto: "premium_tier_0_modal_dismissed_at"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.dismissedContents) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._lastDismissedOutboundPromotionStartDate) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._premiumTier0ModalDismissedAt) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.dismissedContents.isEmpty {
      try visitor.visitSingularBytesField(value: self.dismissedContents, fieldNumber: 1)
    }
    try { if let v = self._lastDismissedOutboundPromotionStartDate {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._premiumTier0ModalDismissedAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: UserContentSettings, rhs: UserContentSettings) -> Bool {
    if lhs.dismissedContents != rhs.dismissedContents {return false}
    if lhs._lastDismissedOutboundPromotionStartDate != rhs._lastDismissedOutboundPromotionStartDate {return false}
    if lhs._premiumTier0ModalDismissedAt != rhs._premiumTier0ModalDismissedAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
